### PR TITLE
updates.tsx changes

### PR DESCRIPTION
**Pull request by vtalatam05**
made the changes and added spacing between the navbar elements. Imported the required pictures

### CODE REVIEW

**Comment by vvs-basanth** [comment]
Okay, I will review and let you know!

**Comment by vvs-basanth** [comment]
Hello, I do not see why the components are added to this PR.
Please explain the usage of the components images in `./public`.


Thank you.

**Comment by vtalatam05** [comment]
this pull request was supposed to be about the changes made to the navbar to increase spacing between the elements. I have mistakenly named the pr as updates.tsx instead of Navbar.tsx
I have also renamed the components to update.png as they are not components but images.

**Comment by vvs-basanth** [comment]
Update the careers page in the navbar as well.
somewhat like this:
image

Thank you

**Comment by vvs-basanth** [comment]
Do the necessary changes mentioned above.

**Pull request closed without merging**
